echo -e "\t\e[31m***********************************************************\e[0m"
echo -e "\t\e[1m\e[101m\e[5m\t\e[4mWARNING : Check for following possible bugs:\e[0m"
echo -e "\t0)\e[0m\e[32m Variable Shadowing?? \e[91mCheck for \e[1mMAXN, EPS, INF!!!\e[0m"
echo -e "\t1)\e[0m\e[93m TEST on ATLEAST 10 hard testcases before submitting!\e[0m"
echo -e "\t2)\e[0m\e[32m Make Tests Cases On The Fly! \e[91mNeed to try stress testing?\e[0m"
echo -e "\t3)\e[0m\e[36m Check for corner cases, and all end points!\e[0m"
echo -e "\t4)\e[0m\e[93m Check for \e[1minteger overflow,\e[0m product of two int!\e[0m"
echo -e "\t5)\e[1m\e[32m int -> long long ?? \e[36mint * 1LL or %d -> %ld??\e[0m"
echo -e "\t6)\e[0m\e[91m floating point precision?? \e[32m setprecision?? \e[1m%.9f?? \e[0m"
echo -e "\t7)\e[0m\e[32m Use \e[1masserts\e[0m to avoid RTE on assumptions!\e[0m"
echo -e "\t8)\e[0m\e[32m \e[1m==\e[0m operator?? Index out of bounds??\e[0m"
echo -e "\t9)\e[0m\e[32m matrix \e[1mm x n or n x m??\e[0m \e[91mprinting the white spaces??\e[0m"
echo -e "\n\t    \e[4m\e[1m\e[37mNOT YET?? TRY different or add something new here!!!\e[91m\e[0m"
echo -e "\t\e[31m*************************mr.convict************************\e[0m"
